# Generated by Django 2.1.5 on 2021-08-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20210730_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='actors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='page',
            name='director',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='page',
            name='poster',
            field=models.ImageField(blank=True, upload_to='movie_poster'),
        ),
    ]
