# Generated by Django 2.1.5 on 2021-08-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20210802_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='poster',
            field=models.ImageField(blank=True, upload_to='movie_posters'),
        ),
    ]
